STOCKS = [
    # ================= BANKS (25)
    "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS",
    "SBIN.NS","AXISBANK.NS","KOTAKBANK.NS","INDUSINDBK.NS","PNB.NS",
    "BANKBARODA.NS","CANBK.NS","IDFCFIRSTB.NS","FEDERALBNK.NS","AUBANK.NS",
    "BANDHANBNK.NS","RBLBANK.NS","YESBANK.NS","KARURVYSYA.NS","DCBBANK.NS",
    "UNIONBANK.NS","IOB.NS","MAHABANK.NS","SOUTHBANK.NS","J&KBANK.NS",

    # ================= NBFC / FINANCE (25)
    "BAJFINANCE.NS","BAJAJFINSV.NS","CHOLAFIN.NS","MUTHOOTFIN.NS","MANAPPURAM.NS",
    "HDFCLIFE.NS","SBILIFE.NS","ICICIPRULI.NS","LICHSGFIN.NS","PFC.NS",
    "RECLTD.NS","IIFL.NS","SBICARD.NS","CRISIL.NS","HUDCO.NS",
    "LTF.NS","MOTILALOFS.NS","KFINTECH.NS","POONAWALLA.NS","SHRIRAMFIN.NS",
    "JMFINANCIL.NS","CANFINHOME.NS","APTUS.NS","AAVAS.NS","IRFC.NS",

    # ================= IT (25)
    "WIPRO.NS","HCLTECH.NS","TECHM.NS","LTIM.NS","PERSISTENT.NS",
    "COFORGE.NS","MPHASIS.NS","OFSS.NS","TATAELXSI.NS","KPITTECH.NS",
    "CYIENT.NS","NAUKRI.NS","TCS.NS","INFY.NS","ZENSARTECH.NS",
    "SONATSOFTW.NS","BSOFT.NS","RAMCOSYS.NS","HAPPSTMNDS.NS","LTTS.NS",
    "NEWGEN.NS","FSL.NS","MASTEK.NS","HEXAWARE.NS","POLICYBZR.NS",

    # ================= OIL & GAS (20)
    "ONGC.NS","IOC.NS","BPCL.NS","GAIL.NS","OIL.NS",
    "PETRONET.NS","IGL.NS","MGL.NS","ATGL.NS","GSPL.NS",
    "HINDPETRO.NS","RELIANCE.NS","CASTROLIND.NS","OLECTRA.NS","SHRIRAMPPS.NS",
    "INOXGAS.NS","TATAPOWER.NS","ADANIGREEN.NS","ADANIPOWER.NS","POWERGRID.NS",

    # ================= PHARMA (20)
    "SUNPHARMA.NS","DRREDDY.NS","CIPLA.NS","DIVISLAB.NS","LUPIN.NS",
    "BIOCON.NS","TORNTPHARM.NS","ALKEM.NS","ZYDUSLIFE.NS","AUROPHARMA.NS",
    "GLENMARK.NS","IPCALAB.NS","LAURUSLABS.NS","PFIZER.NS","ABBOTINDIA.NS",
    "SANOFI.NS","GRANULES.NS","FDC.NS","CAPLIPOINT.NS","JBCHEPHARM.NS",

    # ================= AUTO (20)
    "MARUTI.NS","TATAMOTORS.NS","M&M.NS","EICHERMOT.NS","BAJAJ-AUTO.NS",
    "HEROMOTOCO.NS","TVSMOTOR.NS","ASHOKLEY.NS","BALKRISIND.NS","MRF.NS",
    "CEATLTD.NS","EXIDEIND.NS","AMARAJABAT.NS","SONACOMS.NS","MOTHERSON.NS",
    "BOSCHLTD.NS","TIINDIA.NS","FORCEMOT.NS","JTEKTINDIA.NS","UNOMINDA.NS",

    # ================= FMCG (20)
    "HINDUNILVR.NS","ITC.NS","NESTLEIND.NS","BRITANNIA.NS","DABUR.NS",
    "MARICO.NS","COLPAL.NS","GODREJCP.NS","TATACONSUM.NS","UBL.NS",
    "VBL.NS","RADICO.NS","GILLETTE.NS","EMAMILTD.NS","LTFOODS.NS",
    "ADFFOODS.NS","SULA.NS","JUBLFOOD.NS","WESTLIFE.NS","DEVYANI.NS",

    # ================= METALS (20)
    "TATASTEEL.NS","JSWSTEEL.NS","HINDALCO.NS","VEDL.NS","NMDC.NS",
    "SAIL.NS","JINDALSTEL.NS","NATIONALUM.NS","HINDZINC.NS","APLAPOLLO.NS",
    "MOIL.NS","RATNAMANI.NS","WELCORP.NS","JSL.NS","JSWENERGY.NS",
    "ADANIENT.NS","ADANIPORTS.NS","HINDCOPPER.NS","GMEX.NS","ASHAPURMIN.NS",

    # ================= REAL ESTATE / INFRA (20)
    "DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","PRESTIGE.NS","PHOENIXLTD.NS",
    "BRIGADE.NS","LODHA.NS","IRB.NS","GMRINFRA.NS","NCC.NS",
    "PNCINFRA.NS","KEC.NS","LT.NS","SIEMENS.NS","ABB.NS",
    "BHEL.NS","BEL.NS","RVNL.NS","HFCL.NS","RAILTEL.NS",

    # ================= MISC / GROWTH (30)
    "ZOMATO.NS","PAYTM.NS","NYKAA.NS","IRCTC.NS","DMART.NS",
    "TITAN.NS","TRENT.NS","PAGEIND.NS","ABFRL.NS","MANYAVAR.NS",
    "PIDILITIND.NS","SRF.NS","DEEPAKNTR.NS","AARTIIND.NS","NAVINFLUOR.NS",
    "SUPREMEIND.NS","POLYCAB.NS","HAVELLS.NS","CROMPTON.NS","VOLTAS.NS",
    "BLUEDART.NS","CONCOR.NS","DELHIVERY.NS","BSE.NS","CDSL.NS",
    "MCX.NS","IEX.NS","ANGELONE.NS","HDFCAMC.NS","NAM-INDIA.NS"
]

INTERVAL = "5m"
PERIOD = "7d"

BUY_THRESHOLD = 65
SELL_THRESHOLD = 35
